<?php
/**
 * IndexInstancesApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mayan EDMS API
 *
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\Edms\OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use App\Edms\OpenAPI\Client\Exceptions\ApiException;
use App\Edms\OpenAPI\Client\Authentication\Configuration;
use App\Edms\OpenAPI\Client\Helpers\HeaderSelector;
use App\Edms\OpenAPI\Client\Helpers\ObjectSerializer;

/**
 * IndexInstancesApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IndexInstancesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation indexInstancesList
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\InlineResponse20026
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesList($page = null)
    {
        list($response) = $this->indexInstancesListWithHttpInfo($page);
        return $response;
    }

    /**
     * Operation indexInstancesListWithHttpInfo
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\InlineResponse20026, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesListWithHttpInfo($page = null)
    {
        $request = $this->indexInstancesListRequest($page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\App\Edms\\OpenAPI\Client\Models\InlineResponse20026' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\Edms\\OpenAPI\Client\Models\InlineResponse20026', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\Edms\\OpenAPI\Client\Models\InlineResponse20026';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Edms\\OpenAPI\Client\Models\InlineResponse20026',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation indexInstancesListAsync
     *
     *
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesListAsync($page = null)
    {
        return $this->indexInstancesListAsyncWithHttpInfo($page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation indexInstancesListAsyncWithHttpInfo
     *
     *
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesListAsyncWithHttpInfo($page = null)
    {
        $returnType = '\App\Edms\\OpenAPI\Client\Models\InlineResponse20026';
        $request = $this->indexInstancesListRequest($page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'indexInstancesList'
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function indexInstancesListRequest($page = null)
    {

        $resourcePath = '/index_instances/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, '', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation indexInstancesNodesDocumentsList
     *
     * @param  string $index_instance_id index_instance_id (required)
     * @param  string $index_instance_node_id index_instance_node_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\InlineResponse2006
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesNodesDocumentsList($index_instance_id, $index_instance_node_id, $page = null)
    {
        list($response) = $this->indexInstancesNodesDocumentsListWithHttpInfo($index_instance_id, $index_instance_node_id, $page);
        return $response;
    }

    /**
     * Operation indexInstancesNodesDocumentsListWithHttpInfo
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\InlineResponse2006, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesNodesDocumentsListWithHttpInfo($index_instance_id, $index_instance_node_id, $page = null)
    {
        $request = $this->indexInstancesNodesDocumentsListRequest($index_instance_id, $index_instance_node_id, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\App\Edms\\OpenAPI\Client\Models\InlineResponse2006' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\Edms\\OpenAPI\Client\Models\InlineResponse2006', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\Edms\\OpenAPI\Client\Models\InlineResponse2006';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Edms\\OpenAPI\Client\Models\InlineResponse2006',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation indexInstancesNodesDocumentsListAsync
     *
     *
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesNodesDocumentsListAsync($index_instance_id, $index_instance_node_id, $page = null)
    {
        return $this->indexInstancesNodesDocumentsListAsyncWithHttpInfo($index_instance_id, $index_instance_node_id, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation indexInstancesNodesDocumentsListAsyncWithHttpInfo
     *
     *
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesNodesDocumentsListAsyncWithHttpInfo($index_instance_id, $index_instance_node_id, $page = null)
    {
        $returnType = '\App\Edms\\OpenAPI\Client\Models\InlineResponse2006';
        $request = $this->indexInstancesNodesDocumentsListRequest($index_instance_id, $index_instance_node_id, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'indexInstancesNodesDocumentsList'
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function indexInstancesNodesDocumentsListRequest($index_instance_id, $index_instance_node_id, $page = null)
    {
        // verify the required parameter 'index_instance_id' is set
        if ($index_instance_id === null || (is_array($index_instance_id) && count($index_instance_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_instance_id when calling indexInstancesNodesDocumentsList'
            );
        }
        // verify the required parameter 'index_instance_node_id' is set
        if ($index_instance_node_id === null || (is_array($index_instance_node_id) && count($index_instance_node_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_instance_node_id when calling indexInstancesNodesDocumentsList'
            );
        }

        $resourcePath = '/index_instances/{index_instance_id}/nodes/{index_instance_node_id}/documents/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, '', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }


        // path params
        if ($index_instance_id !== null) {
            $resourcePath = str_replace(
                '{' . 'index_instance_id' . '}',
                ObjectSerializer::toPathValue($index_instance_id),
                $resourcePath
            );
        }
        // path params
        if ($index_instance_node_id !== null) {
            $resourcePath = str_replace(
                '{' . 'index_instance_node_id' . '}',
                ObjectSerializer::toPathValue($index_instance_node_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation indexInstancesNodesList
     *
     * @param  string $index_instance_id index_instance_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\InlineResponse2009
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesNodesList($index_instance_id, $page = null)
    {
        list($response) = $this->indexInstancesNodesListWithHttpInfo($index_instance_id, $page);
        return $response;
    }

    /**
     * Operation indexInstancesNodesListWithHttpInfo
     *
     * @param  string $index_instance_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\InlineResponse2009, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesNodesListWithHttpInfo($index_instance_id, $page = null)
    {
        $request = $this->indexInstancesNodesListRequest($index_instance_id, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\App\Edms\\OpenAPI\Client\Models\InlineResponse2009' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\Edms\\OpenAPI\Client\Models\InlineResponse2009', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\Edms\\OpenAPI\Client\Models\InlineResponse2009';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Edms\\OpenAPI\Client\Models\InlineResponse2009',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation indexInstancesNodesListAsync
     *
     *
     *
     * @param  string $index_instance_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesNodesListAsync($index_instance_id, $page = null)
    {
        return $this->indexInstancesNodesListAsyncWithHttpInfo($index_instance_id, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation indexInstancesNodesListAsyncWithHttpInfo
     *
     *
     *
     * @param  string $index_instance_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesNodesListAsyncWithHttpInfo($index_instance_id, $page = null)
    {
        $returnType = '\App\Edms\\OpenAPI\Client\Models\InlineResponse2009';
        $request = $this->indexInstancesNodesListRequest($index_instance_id, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'indexInstancesNodesList'
     *
     * @param  string $index_instance_id (required)
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function indexInstancesNodesListRequest($index_instance_id, $page = null)
    {
        // verify the required parameter 'index_instance_id' is set
        if ($index_instance_id === null || (is_array($index_instance_id) && count($index_instance_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_instance_id when calling indexInstancesNodesList'
            );
        }

        $resourcePath = '/index_instances/{index_instance_id}/nodes/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, '', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }


        // path params
        if ($index_instance_id !== null) {
            $resourcePath = str_replace(
                '{' . 'index_instance_id' . '}',
                ObjectSerializer::toPathValue($index_instance_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation indexInstancesNodesRead
     *
     * @param  string $index_instance_id index_instance_id (required)
     * @param  string $index_instance_node_id index_instance_node_id (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\IndexInstanceNode
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesNodesRead($index_instance_id, $index_instance_node_id)
    {
        list($response) = $this->indexInstancesNodesReadWithHttpInfo($index_instance_id, $index_instance_node_id);
        return $response;
    }

    /**
     * Operation indexInstancesNodesReadWithHttpInfo
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\IndexInstanceNode, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesNodesReadWithHttpInfo($index_instance_id, $index_instance_node_id)
    {
        $request = $this->indexInstancesNodesReadRequest($index_instance_id, $index_instance_node_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\App\Edms\\OpenAPI\Client\Models\IndexInstanceNode' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\Edms\\OpenAPI\Client\Models\IndexInstanceNode', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\Edms\\OpenAPI\Client\Models\IndexInstanceNode';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Edms\\OpenAPI\Client\Models\IndexInstanceNode',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation indexInstancesNodesReadAsync
     *
     *
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesNodesReadAsync($index_instance_id, $index_instance_node_id)
    {
        return $this->indexInstancesNodesReadAsyncWithHttpInfo($index_instance_id, $index_instance_node_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation indexInstancesNodesReadAsyncWithHttpInfo
     *
     *
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesNodesReadAsyncWithHttpInfo($index_instance_id, $index_instance_node_id)
    {
        $returnType = '\App\Edms\\OpenAPI\Client\Models\IndexInstanceNode';
        $request = $this->indexInstancesNodesReadRequest($index_instance_id, $index_instance_node_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'indexInstancesNodesRead'
     *
     * @param  string $index_instance_id (required)
     * @param  string $index_instance_node_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function indexInstancesNodesReadRequest($index_instance_id, $index_instance_node_id)
    {
        // verify the required parameter 'index_instance_id' is set
        if ($index_instance_id === null || (is_array($index_instance_id) && count($index_instance_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_instance_id when calling indexInstancesNodesRead'
            );
        }
        // verify the required parameter 'index_instance_node_id' is set
        if ($index_instance_node_id === null || (is_array($index_instance_node_id) && count($index_instance_node_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_instance_node_id when calling indexInstancesNodesRead'
            );
        }

        $resourcePath = '/index_instances/{index_instance_id}/nodes/{index_instance_node_id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($index_instance_id !== null) {
            $resourcePath = str_replace(
                '{' . 'index_instance_id' . '}',
                ObjectSerializer::toPathValue($index_instance_id),
                $resourcePath
            );
        }
        // path params
        if ($index_instance_node_id !== null) {
            $resourcePath = str_replace(
                '{' . 'index_instance_node_id' . '}',
                ObjectSerializer::toPathValue($index_instance_node_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation indexInstancesRead
     *
     * @param  string $index_instance_id index_instance_id (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\IndexInstance
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesRead($index_instance_id)
    {
        list($response) = $this->indexInstancesReadWithHttpInfo($index_instance_id);
        return $response;
    }

    /**
     * Operation indexInstancesReadWithHttpInfo
     *
     * @param  string $index_instance_id (required)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\IndexInstance, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function indexInstancesReadWithHttpInfo($index_instance_id)
    {
        $request = $this->indexInstancesReadRequest($index_instance_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\App\Edms\\OpenAPI\Client\Models\IndexInstance' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\Edms\\OpenAPI\Client\Models\IndexInstance', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\Edms\\OpenAPI\Client\Models\IndexInstance';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Edms\\OpenAPI\Client\Models\IndexInstance',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation indexInstancesReadAsync
     *
     *
     *
     * @param  string $index_instance_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesReadAsync($index_instance_id)
    {
        return $this->indexInstancesReadAsyncWithHttpInfo($index_instance_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation indexInstancesReadAsyncWithHttpInfo
     *
     *
     *
     * @param  string $index_instance_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indexInstancesReadAsyncWithHttpInfo($index_instance_id)
    {
        $returnType = '\App\Edms\\OpenAPI\Client\Models\IndexInstance';
        $request = $this->indexInstancesReadRequest($index_instance_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'indexInstancesRead'
     *
     * @param  string $index_instance_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function indexInstancesReadRequest($index_instance_id)
    {
        // verify the required parameter 'index_instance_id' is set
        if ($index_instance_id === null || (is_array($index_instance_id) && count($index_instance_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_instance_id when calling indexInstancesRead'
            );
        }

        $resourcePath = '/index_instances/{index_instance_id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($index_instance_id !== null) {
            $resourcePath = str_replace(
                '{' . 'index_instance_id' . '}',
                ObjectSerializer::toPathValue($index_instance_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
