<?php
/**
 * StagingFoldersApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mayan EDMS API
 *
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\Edms\OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use App\Edms\OpenAPI\Client\Exceptions\ApiException;
use App\Edms\OpenAPI\Client\Authentication\Configuration;
use App\Edms\OpenAPI\Client\Helpers\HeaderSelector;
use App\Edms\OpenAPI\Client\Helpers\ObjectSerializer;

/**
 * StagingFoldersApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StagingFoldersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param \Disme\Support\ExternalIntegrations\OpenAPI\Client\Authentication\Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation stagingFoldersCreate
     *
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data data (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersCreate($data)
    {
        list($response) = $this->stagingFoldersCreateWithHttpInfo($data);
        return $response;
    }

    /**
     * Operation stagingFoldersCreateWithHttpInfo
     *
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return array of \OpenAPI\Client\Model\StagingFolder, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersCreateWithHttpInfo($data)
    {
        $request = $this->stagingFoldersCreateRequest($data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 201:
                    if ('App\Edms\OpenAPI\Client\Models\StagingFolder' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\StagingFolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\StagingFolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersCreateAsync
     *
     *
     *
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersCreateAsync($data)
    {
        return $this->stagingFoldersCreateAsyncWithHttpInfo($data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersCreateAsyncWithHttpInfo
     *
     *
     *
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersCreateAsyncWithHttpInfo($data)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
        $request = $this->stagingFoldersCreateRequest($data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersCreate'
     *
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Psr7\Request
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersCreateRequest($data)
    {
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling stagingFoldersCreate'
            );
        }

        $resourcePath = '/staging_folders/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($data)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersDelete
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @return void
     * @throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersDelete($id)
    {
        $this->stagingFoldersDeleteWithHttpInfo($id);
    }

    /**
     * Operation stagingFoldersDeleteWithHttpInfo
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersDeleteWithHttpInfo($id)
    {
        $request = $this->stagingFoldersDeleteRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersDeleteAsync
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersDeleteAsync($id)
    {
        return $this->stagingFoldersDeleteAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersDeleteAsyncWithHttpInfo
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersDeleteAsyncWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->stagingFoldersDeleteRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersDelete'
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stagingFoldersDeleteRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling stagingFoldersDelete'
            );
        }

        $resourcePath = '/staging_folders/{id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersFileDelete
     *
     * @param  string $encoded_filename encoded_filename (required)
     * @param  string $staging_folder_pk staging_folder_pk (required)
     *
     * @return void
     * @throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileDelete($encoded_filename, $staging_folder_pk)
    {
        $this->stagingFoldersFileDeleteWithHttpInfo($encoded_filename, $staging_folder_pk);
    }

    /**
     * Operation stagingFoldersFileDeleteWithHttpInfo
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileDeleteWithHttpInfo($encoded_filename, $staging_folder_pk)
    {
        $request = $this->stagingFoldersFileDeleteRequest($encoded_filename, $staging_folder_pk);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersFileDeleteAsync
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersFileDeleteAsync($encoded_filename, $staging_folder_pk)
    {
        return $this->stagingFoldersFileDeleteAsyncWithHttpInfo($encoded_filename, $staging_folder_pk)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersFileDeleteAsyncWithHttpInfo
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersFileDeleteAsyncWithHttpInfo($encoded_filename, $staging_folder_pk)
    {
        $returnType = '';
        $request = $this->stagingFoldersFileDeleteRequest($encoded_filename, $staging_folder_pk);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersFileDelete'
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stagingFoldersFileDeleteRequest($encoded_filename, $staging_folder_pk)
    {
        // verify the required parameter 'encoded_filename' is set
        if ($encoded_filename === null || (is_array($encoded_filename) && count($encoded_filename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $encoded_filename when calling stagingFoldersFileDelete'
            );
        }
        // verify the required parameter 'staging_folder_pk' is set
        if ($staging_folder_pk === null || (is_array($staging_folder_pk) && count($staging_folder_pk) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $staging_folder_pk when calling stagingFoldersFileDelete'
            );
        }

        $resourcePath = '/staging_folders/file/{staging_folder_pk}/{encoded_filename}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($encoded_filename !== null) {
            $resourcePath = str_replace(
                '{' . 'encoded_filename' . '}',
                ObjectSerializer::toPathValue($encoded_filename),
                $resourcePath
            );
        }
        // path params
        if ($staging_folder_pk !== null) {
            $resourcePath = str_replace(
                '{' . 'staging_folder_pk' . '}',
                ObjectSerializer::toPathValue($staging_folder_pk),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersFileImageRead
     *
     * @param  string $encoded_filename encoded_filename (required)
     * @param  string $staging_folder_pk staging_folder_pk (required)
     *
     * @return void
     * @throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileImageRead($encoded_filename, $staging_folder_pk)
    {
        $this->stagingFoldersFileImageReadWithHttpInfo($encoded_filename, $staging_folder_pk);
    }

    /**
     * Operation stagingFoldersFileImageReadWithHttpInfo
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileImageReadWithHttpInfo($encoded_filename, $staging_folder_pk)
    {
        $request = $this->stagingFoldersFileImageReadRequest($encoded_filename, $staging_folder_pk);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersFileImageReadAsync
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersFileImageReadAsync($encoded_filename, $staging_folder_pk)
    {
        return $this->stagingFoldersFileImageReadAsyncWithHttpInfo($encoded_filename, $staging_folder_pk)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersFileImageReadAsyncWithHttpInfo
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersFileImageReadAsyncWithHttpInfo($encoded_filename, $staging_folder_pk)
    {
        $returnType = '';
        $request = $this->stagingFoldersFileImageReadRequest($encoded_filename, $staging_folder_pk);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersFileImageRead'
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stagingFoldersFileImageReadRequest($encoded_filename, $staging_folder_pk)
    {
        // verify the required parameter 'encoded_filename' is set
        if ($encoded_filename === null || (is_array($encoded_filename) && count($encoded_filename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $encoded_filename when calling stagingFoldersFileImageRead'
            );
        }
        // verify the required parameter 'staging_folder_pk' is set
        if ($staging_folder_pk === null || (is_array($staging_folder_pk) && count($staging_folder_pk) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $staging_folder_pk when calling stagingFoldersFileImageRead'
            );
        }

        $resourcePath = '/staging_folders/file/{staging_folder_pk}/{encoded_filename}/image/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($encoded_filename !== null) {
            $resourcePath = str_replace(
                '{' . 'encoded_filename' . '}',
                ObjectSerializer::toPathValue($encoded_filename),
                $resourcePath
            );
        }
        // path params
        if ($staging_folder_pk !== null) {
            $resourcePath = str_replace(
                '{' . 'staging_folder_pk' . '}',
                ObjectSerializer::toPathValue($staging_folder_pk),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersFileRead
     *
     * @param  string $encoded_filename encoded_filename (required)
     * @param  string $staging_folder_pk staging_folder_pk (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFile
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileRead($encoded_filename, $staging_folder_pk)
    {
        list($response) = $this->stagingFoldersFileReadWithHttpInfo($encoded_filename, $staging_folder_pk);
        return $response;
    }

    /**
     * Operation stagingFoldersFileReadWithHttpInfo
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\StagingFolderFile, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileReadWithHttpInfo($encoded_filename, $staging_folder_pk)
    {
        $request = $this->stagingFoldersFileReadRequest($encoded_filename, $staging_folder_pk);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('App\Edms\OpenAPI\Client\Models\StagingFolderFile' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\StagingFolderFile', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolderFile';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\StagingFolderFile',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersFileReadAsync
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersFileReadAsync($encoded_filename, $staging_folder_pk)
    {
        return $this->stagingFoldersFileReadAsyncWithHttpInfo($encoded_filename, $staging_folder_pk)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersFileReadAsyncWithHttpInfo
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersFileReadAsyncWithHttpInfo($encoded_filename, $staging_folder_pk)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolderFile';
        $request = $this->stagingFoldersFileReadRequest($encoded_filename, $staging_folder_pk);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersFileRead'
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stagingFoldersFileReadRequest($encoded_filename, $staging_folder_pk)
    {
        // verify the required parameter 'encoded_filename' is set
        if ($encoded_filename === null || (is_array($encoded_filename) && count($encoded_filename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $encoded_filename when calling stagingFoldersFileRead'
            );
        }
        // verify the required parameter 'staging_folder_pk' is set
        if ($staging_folder_pk === null || (is_array($staging_folder_pk) && count($staging_folder_pk) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $staging_folder_pk when calling stagingFoldersFileRead'
            );
        }

        $resourcePath = '/staging_folders/file/{staging_folder_pk}/{encoded_filename}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($encoded_filename !== null) {
            $resourcePath = str_replace(
                '{' . 'encoded_filename' . '}',
                ObjectSerializer::toPathValue($encoded_filename),
                $resourcePath
            );
        }
        // path params
        if ($staging_folder_pk !== null) {
            $resourcePath = str_replace(
                '{' . 'staging_folder_pk' . '}',
                ObjectSerializer::toPathValue($staging_folder_pk),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersFileUploadCreate
     *
     * @param  string $encoded_filename encoded_filename (required)
     * @param  string $staging_folder_pk staging_folder_pk (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFileUpload $data data (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFileUpload
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileUploadCreate($encoded_filename, $staging_folder_pk, $data)
    {
        list($response) = $this->stagingFoldersFileUploadCreateWithHttpInfo($encoded_filename, $staging_folder_pk, $data);
        return $response;
    }

    /**
     * Operation stagingFoldersFileUploadCreateWithHttpInfo
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFileUpload $data (required)
     *
     * @return array of \OpenAPI\Client\Model\StagingFolderFileUpload, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersFileUploadCreateWithHttpInfo($encoded_filename, $staging_folder_pk, $data)
    {
        $request = $this->stagingFoldersFileUploadCreateRequest($encoded_filename, $staging_folder_pk, $data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 201:
                    if ('App\Edms\OpenAPI\Client\Models\StagingFolderFileUpload' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\StagingFolderFileUpload', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolderFileUpload';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\StagingFolderFileUpload',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersFileUploadCreateAsync
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFileUpload $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersFileUploadCreateAsync($encoded_filename, $staging_folder_pk, $data)
    {
        return $this->stagingFoldersFileUploadCreateAsyncWithHttpInfo($encoded_filename, $staging_folder_pk, $data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersFileUploadCreateAsyncWithHttpInfo
     *
     *
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFileUpload $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersFileUploadCreateAsyncWithHttpInfo($encoded_filename, $staging_folder_pk, $data)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolderFileUpload';
        $request = $this->stagingFoldersFileUploadCreateRequest($encoded_filename, $staging_folder_pk, $data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersFileUploadCreate'
     *
     * @param  string $encoded_filename (required)
     * @param  string $staging_folder_pk (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolderFileUpload $data (required)
     *
     * @return \GuzzleHttp\Psr7\Request
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersFileUploadCreateRequest($encoded_filename, $staging_folder_pk, $data)
    {
        // verify the required parameter 'encoded_filename' is set
        if ($encoded_filename === null || (is_array($encoded_filename) && count($encoded_filename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $encoded_filename when calling stagingFoldersFileUploadCreate'
            );
        }
        // verify the required parameter 'staging_folder_pk' is set
        if ($staging_folder_pk === null || (is_array($staging_folder_pk) && count($staging_folder_pk) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $staging_folder_pk when calling stagingFoldersFileUploadCreate'
            );
        }
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling stagingFoldersFileUploadCreate'
            );
        }

        $resourcePath = '/staging_folders/file/{staging_folder_pk}/{encoded_filename}/upload/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($encoded_filename !== null) {
            $resourcePath = str_replace(
                '{' . 'encoded_filename' . '}',
                ObjectSerializer::toPathValue($encoded_filename),
                $resourcePath
            );
        }
        // path params
        if ($staging_folder_pk !== null) {
            $resourcePath = str_replace(
                '{' . 'staging_folder_pk' . '}',
                ObjectSerializer::toPathValue($staging_folder_pk),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($data)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersList
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\InlineResponse20040
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersList($page = null)
    {
        list($response) = $this->stagingFoldersListWithHttpInfo($page);
        return $response;
    }

    /**
     * Operation stagingFoldersListWithHttpInfo
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\InlineResponse20040, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersListWithHttpInfo($page = null)
    {
        $request = $this->stagingFoldersListRequest($page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('App\Edms\OpenAPI\Client\Models\InlineResponse20040' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\InlineResponse20040', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\InlineResponse20040';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\InlineResponse20040',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersListAsync
     *
     *
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersListAsync($page = null)
    {
        return $this->stagingFoldersListAsyncWithHttpInfo($page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersListAsyncWithHttpInfo
     *
     *
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersListAsyncWithHttpInfo($page = null)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\InlineResponse20040';
        $request = $this->stagingFoldersListRequest($page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersList'
     *
     * @param  int $page A page number within the paginated result set. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stagingFoldersListRequest($page = null)
    {

        $resourcePath = '/staging_folders/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, '', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersPartialUpdate
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data data (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersPartialUpdate($id, $data)
    {
        list($response) = $this->stagingFoldersPartialUpdateWithHttpInfo($id, $data);
        return $response;
    }

    /**
     * Operation stagingFoldersPartialUpdateWithHttpInfo
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return array of \OpenAPI\Client\Model\StagingFolder, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersPartialUpdateWithHttpInfo($id, $data)
    {
        $request = $this->stagingFoldersPartialUpdateRequest($id, $data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('App\Edms\OpenAPI\Client\Models\StagingFolder' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\StagingFolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\StagingFolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersPartialUpdateAsync
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersPartialUpdateAsync($id, $data)
    {
        return $this->stagingFoldersPartialUpdateAsyncWithHttpInfo($id, $data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersPartialUpdateAsyncWithHttpInfo
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersPartialUpdateAsyncWithHttpInfo($id, $data)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
        $request = $this->stagingFoldersPartialUpdateRequest($id, $data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersPartialUpdate'
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Psr7\Request
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersPartialUpdateRequest($id, $data)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling stagingFoldersPartialUpdate'
            );
        }
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling stagingFoldersPartialUpdate'
            );
        }

        $resourcePath = '/staging_folders/{id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($data)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersRead
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersRead($id)
    {
        list($response) = $this->stagingFoldersReadWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation stagingFoldersReadWithHttpInfo
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @return array of \app\App\Edms\OpenAPI\Client\Models\StagingFolder, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersReadWithHttpInfo($id)
    {
        $request = $this->stagingFoldersReadRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('App\Edms\OpenAPI\Client\Models\StagingFolder' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\StagingFolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\StagingFolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersReadAsync
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersReadAsync($id)
    {
        return $this->stagingFoldersReadAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersReadAsyncWithHttpInfo
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stagingFoldersReadAsyncWithHttpInfo($id)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
        $request = $this->stagingFoldersReadRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersRead'
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stagingFoldersReadRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling stagingFoldersRead'
            );
        }

        $resourcePath = '/staging_folders/{id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stagingFoldersUpdate
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data data (required)
     *
     * @return \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersUpdate($id, $data)
    {
        list($response) = $this->stagingFoldersUpdateWithHttpInfo($id, $data);
        return $response;
    }

    /**
     * Operation stagingFoldersUpdateWithHttpInfo
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return array of \OpenAPI\Client\Model\StagingFolder, HTTP status code, HTTP response headers (array of strings)
     *@throws \InvalidArgumentException
     * @throws \Disme\Support\ExternalIntegrations\OpenAPI\Client\Exceptions\ApiException on non-2xx response
     */
    public function stagingFoldersUpdateWithHttpInfo($id, $data)
    {
        $request = $this->stagingFoldersUpdateRequest($id, $data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('App\Edms\OpenAPI\Client\Models\StagingFolder' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'App\Edms\OpenAPI\Client\Models\StagingFolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Edms\OpenAPI\Client\Models\StagingFolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation stagingFoldersUpdateAsync
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersUpdateAsync($id, $data)
    {
        return $this->stagingFoldersUpdateAsyncWithHttpInfo($id, $data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stagingFoldersUpdateAsyncWithHttpInfo
     *
     *
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersUpdateAsyncWithHttpInfo($id, $data)
    {
        $returnType = 'App\Edms\OpenAPI\Client\Models\StagingFolder';
        $request = $this->stagingFoldersUpdateRequest($id, $data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stagingFoldersUpdate'
     *
     * @param  int $id A unique integer value identifying this Staging folder. (required)
     * @param  \app\Disme\Support\ExternalIntegrations\OpenAPI\Client\Models\StagingFolder $data (required)
     *
     * @return \GuzzleHttp\Psr7\Request
     *@throws \InvalidArgumentException
     */
    public function stagingFoldersUpdateRequest($id, $data)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling stagingFoldersUpdate'
            );
        }
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling stagingFoldersUpdate'
            );
        }

        $resourcePath = '/staging_folders/{id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($data)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($data));
            } else {
                $httpBody = $data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic auth
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
