<?php
/*
 * Copyright © 2016 - 2024  Enterprise Engineering Lab /
 * University of Madeira /Regional Agency for the Development of Research, Technology and Innovation - ARDITI
 */

use Illuminate\Database\Seeder;
use App\TransactionType;
use App\TransactionTypeName;

class TransactionTypeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        TransactionType::insert([
            array('id' => '1', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '1', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '2', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '2', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '12', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '3', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '0', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '4', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '0', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '5', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '6', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '1', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '0', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '7', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '1', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '8', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '9', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '1', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '10', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '11', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '1', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '12', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '13', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'original', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '14', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'documental', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '15', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'documental', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '16', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'documental', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '17', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'documental', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '18', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'documental', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
            array('id' => '19', 'state' => 'active', 'process_type_id' => '1', 'init_proc' => '0', 'end_proc' => '0', 'interm_task' => '0', 'external' => '0', 'type' => 'documental', 'frontier' => '0', 'frontier_type' => NULL, 'executer_role_id' => '21', 'own_user_access_only' => '1', 'auto_activate' => '0', 'freq_activate' => NULL, 'when_activate' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL),
        ]);

        TransactionTypeName::insert([
            array('transaction_type_id' => '1', 'language_id' => '1', 't_name' => 'Realização de Pedido de Audiência', 'rt_name' => 'Pedido de Audiência foi Realizado', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '2', 'language_id' => '1', 't_name' => 'Seleção do Oficial para Audiência', 'rt_name' => 'Oficial para a Audiência foi selecionado', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '3', 'language_id' => '1', 't_name' => 'Agendamento da Audiência', 'rt_name' => 'Audiência Agendada', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '4', 'language_id' => '1', 't_name' => 'Verificação de Necessidade de Audiência', 'rt_name' => 'Necessidade de Audiência Verificada', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '5', 'language_id' => '1', 't_name' => 'Realização de Audiência', 'rt_name' => 'Audiência Realizada', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '6', 'language_id' => '1', 't_name' => 'Fecho do Processo de Audiência', 'rt_name' => 'Processo de Audiência Fechado', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '7', 'language_id' => '1', 't_name' => 'Gestão do Processo de Audiências', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '8', 'language_id' => '1', 't_name' => 'Gestão de Audiência', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '9', 'language_id' => '1', 't_name' => 'Reagendamento ou Cancelamento de Audiência', 'rt_name' => 'Audiência Reagendada ou Cancelada', 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '10', 'language_id' => '1', 't_name' => 'Reagendamento em Lote', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '11', 'language_id' => '1', 't_name' => 'Gerir Horário do Oficial para Audiência', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '12', 'language_id' => '1', 't_name' => 'Gerir Vagas de Agendamento de Audiências', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '13', 'language_id' => '1', 't_name' => 'Gerir Audiências Agendadas', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '14', 'language_id' => '1', 't_name' => 'Impressão do Horário Diário', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '15', 'language_id' => '1', 't_name' => 'Impressão da Audiência', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '16', 'language_id' => '1', 't_name' => 'Impressão do Histórico do Requerente', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '17', 'language_id' => '1', 't_name' => 'Gerar Documento de Pedido de Audiência', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '18', 'language_id' => '1', 't_name' => 'Gerar Documento com Informações da Audiência', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
            array('transaction_type_id' => '19', 'language_id' => '1', 't_name' => 'Entrega do Documento', 'rt_name' => NULL, 'updated_by' => NULL, 'deleted_by' => NULL, 'created_at' => NULL, 'updated_at' => NULL, 'deleted_at' => NULL, 'd_name' => ''),
        ]);
    }
}
