<?php
/**
 * WorkflowsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mayan EDMS API
 *
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace App\Edms\OpenAPI\Client\Tests\Api;

use App\Edms\OpenAPI\Client\Authentication\Configuration;
use App\Edms\OpenAPI\Client\Exceptions\ApiException;
use App\Edms\OpenAPI\Client\Helpers\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkflowsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for workflowsCreate
     *
     * .
     *
     */
    public function testWorkflowsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsDelete
     *
     * .
     *
     */
    public function testWorkflowsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsDocumentTypesCreate
     *
     * .
     *
     */
    public function testWorkflowsDocumentTypesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsDocumentTypesDelete
     *
     * .
     *
     */
    public function testWorkflowsDocumentTypesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsDocumentTypesList
     *
     * .
     *
     */
    public function testWorkflowsDocumentTypesList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsDocumentTypesRead
     *
     * .
     *
     */
    public function testWorkflowsDocumentTypesRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsImageRead
     *
     * .
     *
     */
    public function testWorkflowsImageRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsList
     *
     * .
     *
     */
    public function testWorkflowsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsPartialUpdate
     *
     * .
     *
     */
    public function testWorkflowsPartialUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsRead
     *
     * .
     *
     */
    public function testWorkflowsRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsStatesCreate
     *
     * .
     *
     */
    public function testWorkflowsStatesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsStatesDelete
     *
     * .
     *
     */
    public function testWorkflowsStatesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsStatesList
     *
     * .
     *
     */
    public function testWorkflowsStatesList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsStatesPartialUpdate
     *
     * .
     *
     */
    public function testWorkflowsStatesPartialUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsStatesRead
     *
     * .
     *
     */
    public function testWorkflowsStatesRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsStatesUpdate
     *
     * .
     *
     */
    public function testWorkflowsStatesUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsCreate
     *
     * .
     *
     */
    public function testWorkflowsTransitionsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsDelete
     *
     * .
     *
     */
    public function testWorkflowsTransitionsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsFieldsCreate
     *
     * .
     *
     */
    public function testWorkflowsTransitionsFieldsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsFieldsDelete
     *
     * .
     *
     */
    public function testWorkflowsTransitionsFieldsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsFieldsList
     *
     * .
     *
     */
    public function testWorkflowsTransitionsFieldsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsFieldsPartialUpdate
     *
     * .
     *
     */
    public function testWorkflowsTransitionsFieldsPartialUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsFieldsRead
     *
     * .
     *
     */
    public function testWorkflowsTransitionsFieldsRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsFieldsUpdate
     *
     * .
     *
     */
    public function testWorkflowsTransitionsFieldsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsList
     *
     * .
     *
     */
    public function testWorkflowsTransitionsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsPartialUpdate
     *
     * .
     *
     */
    public function testWorkflowsTransitionsPartialUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsRead
     *
     * .
     *
     */
    public function testWorkflowsTransitionsRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsTransitionsUpdate
     *
     * .
     *
     */
    public function testWorkflowsTransitionsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workflowsUpdate
     *
     * .
     *
     */
    public function testWorkflowsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
