<?php
/**
 * WritableDocumentVersionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mayan EDMS API
 *
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * WritableDocumentVersionTest Class Doc Comment
 *
 * @category    Class
 * @description WritableDocumentVersion
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WritableDocumentVersionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WritableDocumentVersion"
     */
    public function testWritableDocumentVersion()
    {
    }

    /**
     * Test attribute "checksum"
     */
    public function testPropertyChecksum()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "document_url"
     */
    public function testPropertyDocumentUrl()
    {
    }

    /**
     * Test attribute "download_url"
     */
    public function testPropertyDownloadUrl()
    {
    }

    /**
     * Test attribute "encoding"
     */
    public function testPropertyEncoding()
    {
    }

    /**
     * Test attribute "file"
     */
    public function testPropertyFile()
    {
    }

    /**
     * Test attribute "mimetype"
     */
    public function testPropertyMimetype()
    {
    }

    /**
     * Test attribute "pages_url"
     */
    public function testPropertyPagesUrl()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }
}
