<?php
/**
 * DocumentTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mayan EDMS API
 *
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentTypesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for documentTypesCreate
     *
     * .
     *
     */
    public function testDocumentTypesCreate()
    {
    }

    /**
     * Test case for documentTypesDelete
     *
     * .
     *
     */
    public function testDocumentTypesDelete()
    {
    }

    /**
     * Test case for documentTypesDocumentsList
     *
     * .
     *
     */
    public function testDocumentTypesDocumentsList()
    {
    }

    /**
     * Test case for documentTypesList
     *
     * .
     *
     */
    public function testDocumentTypesList()
    {
    }

    /**
     * Test case for documentTypesMetadataTypesCreate
     *
     * .
     *
     */
    public function testDocumentTypesMetadataTypesCreate()
    {
    }

    /**
     * Test case for documentTypesMetadataTypesDelete
     *
     * .
     *
     */
    public function testDocumentTypesMetadataTypesDelete()
    {
    }

    /**
     * Test case for documentTypesMetadataTypesList
     *
     * .
     *
     */
    public function testDocumentTypesMetadataTypesList()
    {
    }

    /**
     * Test case for documentTypesMetadataTypesPartialUpdate
     *
     * .
     *
     */
    public function testDocumentTypesMetadataTypesPartialUpdate()
    {
    }

    /**
     * Test case for documentTypesMetadataTypesRead
     *
     * .
     *
     */
    public function testDocumentTypesMetadataTypesRead()
    {
    }

    /**
     * Test case for documentTypesMetadataTypesUpdate
     *
     * .
     *
     */
    public function testDocumentTypesMetadataTypesUpdate()
    {
    }

    /**
     * Test case for documentTypesOcrSettingsPartialUpdate
     *
     * .
     *
     */
    public function testDocumentTypesOcrSettingsPartialUpdate()
    {
    }

    /**
     * Test case for documentTypesOcrSettingsRead
     *
     * .
     *
     */
    public function testDocumentTypesOcrSettingsRead()
    {
    }

    /**
     * Test case for documentTypesOcrSettingsUpdate
     *
     * .
     *
     */
    public function testDocumentTypesOcrSettingsUpdate()
    {
    }

    /**
     * Test case for documentTypesParsingSettingsPartialUpdate
     *
     * .
     *
     */
    public function testDocumentTypesParsingSettingsPartialUpdate()
    {
    }

    /**
     * Test case for documentTypesParsingSettingsRead
     *
     * .
     *
     */
    public function testDocumentTypesParsingSettingsRead()
    {
    }

    /**
     * Test case for documentTypesParsingSettingsUpdate
     *
     * .
     *
     */
    public function testDocumentTypesParsingSettingsUpdate()
    {
    }

    /**
     * Test case for documentTypesPartialUpdate
     *
     * .
     *
     */
    public function testDocumentTypesPartialUpdate()
    {
    }

    /**
     * Test case for documentTypesRead
     *
     * .
     *
     */
    public function testDocumentTypesRead()
    {
    }

    /**
     * Test case for documentTypesUpdate
     *
     * .
     *
     */
    public function testDocumentTypesUpdate()
    {
    }

    /**
     * Test case for documentTypesWorkflowsList
     *
     * .
     *
     */
    public function testDocumentTypesWorkflowsList()
    {
    }
}
