<?php
/**
 * ObjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mayan EDMS API
 *
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ObjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ObjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for objectsAclsCreate
     *
     * .
     *
     */
    public function testObjectsAclsCreate()
    {
    }

    /**
     * Test case for objectsAclsDelete
     *
     * .
     *
     */
    public function testObjectsAclsDelete()
    {
    }

    /**
     * Test case for objectsAclsList
     *
     * .
     *
     */
    public function testObjectsAclsList()
    {
    }

    /**
     * Test case for objectsAclsPermissionsCreate
     *
     * .
     *
     */
    public function testObjectsAclsPermissionsCreate()
    {
    }

    /**
     * Test case for objectsAclsPermissionsDelete
     *
     * .
     *
     */
    public function testObjectsAclsPermissionsDelete()
    {
    }

    /**
     * Test case for objectsAclsPermissionsList
     *
     * .
     *
     */
    public function testObjectsAclsPermissionsList()
    {
    }

    /**
     * Test case for objectsAclsPermissionsRead
     *
     * .
     *
     */
    public function testObjectsAclsPermissionsRead()
    {
    }

    /**
     * Test case for objectsAclsRead
     *
     * .
     *
     */
    public function testObjectsAclsRead()
    {
    }

    /**
     * Test case for objectsEventsList
     *
     * .
     *
     */
    public function testObjectsEventsList()
    {
    }
}
